daysUntilStale: 7
daysUntilClose: 7
exemptMilestones: true
staleLabel: waiting-reply

markComment: >
  Hi there! This has been automatically marked as stale because it has not
  had activity in the past 7 days. It will be closed in 7 days if no
  further activity takes place.

closeComment: >
  Hi there! This has been closed due to lack of activity. Please comment
  if you would like it re-opened.
